start_cook:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: anova_oven
    sous_vide:
      required: false
      default: false
      selector:
        boolean:
    target_temperature_celsius:
      required: false
      selector:
        number:
          min: 20
          max: 250
          unit_of_measurement: "째C"
          mode: slider
      filter:
        supported_features:
          - climate.ClimateEntityFeature.TARGET_TEMPERATURE
    target_temperature_fahrenheit:
      required: false
      selector:
        number:
          min: 68
          max: 482
          unit_of_measurement: "째F"
          mode: slider
      filter:
        supported_features:
          - climate.ClimateEntityFeature.TARGET_HUMIDITY
    heating_top:
      default: false
      selector:
        boolean:
    heating_bottom:
      default: false
      selector:
        boolean:
    heating_rear:
      default: true
      selector:
        boolean:
    temperature_probe_celsius:
      required: false
      selector:
        number:
          min: 20
          max: 250
          unit_of_measurement: "째C"
          mode: slider
      filter:
        supported_features:
          - climate.ClimateEntityFeature.TARGET_TEMPERATURE
    temperature_probe_fahrenheit:
      required: false
      selector:
        number:
          min: 68
          max: 482
          unit_of_measurement: "째F"
          mode: slider
      filter:
        supported_features:
          - climate.ClimateEntityFeature.TARGET_HUMIDITY
    target_humidity:
      required: false
      selector:
        number:
          min: 0
          max: 100
          mode: slider
    timer:
      required: false
      selector:
        duration:
    timer_mode:
      required: false
      selector:
        select:
          mode: dropdown
          options:
            - Immediately
            - When Preheated
            - Manually

stop_cook:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: anova_oven